const a = 10

try{
    console.log(A)
}catch(err){
    console.log("the problem is "+ err)
}


console.log("here i comes")